#ifndef XDR_LANGUNDEF_H
#define XDR_LANGUNDEF_H

#undef BEGIN
#undef END 
#undef CREATE_TEST
#undef CREATE_TEST_AND_USE_COMPARATOR
#undef WITH_MIN_VERSION
#undef WITH_MAX_VERSION
#undef AS
#undef WITH_PRESETS
#undef WHERE
#undef NOTHING_IS_MAPPED
#undef MAP
#undef AND
#undef END_MAPPING
#undef INTERFACE
#undef IMPLEMENTATION_DETAILS

#endif